### ISSUE TITLE
should we always output `---` for all YAML files

### ISSUE THREAD

**Issue by cppforlife** [k14s/ytt#182] opened 2020-08-12 14:52 UTC
currently we do not output first `---` since it's not required by YAML. some folks may appreciate to consistency of always adding that in.

**Comment by pivotaljohn** [comment] 2020-08-12 20:27
And to be clear, we're talking about non-empty documents, yeah?

I ask because I know of a few cases where we rely on skipping empty documents to keep the output sane.

**Comment by cppforlife** [comment] 2020-08-13 16:27
> And to be clear, we're talking about non-empty documents, yeah?

that's right.

**Comment by cari-lynn** [comment] 2021-11-11 20:04
This is a duplicate of #477 , there's some discussion there, so I'm going to close this.

**Closed as completed by cari-lynn** 2021-11-11 20:04 UTC
Labels: enhancement, discussion
