### ISSUE TITLE
Unable to install v0.49.1 by using carvel-dev/setup-action@v2 in GitHub Actions

### ISSUE THREAD

**Issue by jakubbujny** [k14s/ytt#920] opened 2024-06-12 18:17 UTC
GitHub Action:
```
      - uses: carvel-dev/setup-action@v2
        with:
          only: ytt
```
fails with

```
Run carvel-dev/setup-action@v2
  with:
    only: ytt
    ytt: latest
    kbld: latest
    kapp: latest
    kwt: latest
    imgpkg: latest
    vendir: latest
    kctrl: latest
Warning: No token set, you may experience rate limiting. Set "token: ${{ secrets.GITHUB_TOKEN }}" if you have problems.
Installing ytt:latest
Downloading ytt v0.49.1 from https://github.com/carvel-dev/ytt/releases/download/v0.49.1/ytt-linux-amd64
Error: Unable to verify checksum for ytt-linux-amd64. Expected to find "20a2f7466157a9c6189e885d0027e17c48776e65627f30fe04bffeef1d6f6166  ./ytt-linux-amd64" in release notes.
```

I see checksums were added here: https://github.com/carvel-dev/ytt/releases/tag/v0.49.1 
but it still fails for some reason

**Comment by jakubbujny** [comment] 2024-06-12 18:20
ahh I found where is the problem - carvel-dev/setup-action@v2 expects 2 spaces between checksum and binary name but in release notes there is only one space currently

**Comment by jakubbujny** [comment] 2024-06-12 18:23
0.49.0
```
0658db4af8263ca091ca31e4b599cb40c324b75934660a4c0ed98ad9b701f7e9  ./ytt-darwin-arm64
357ec754446b1eda29dd529e088f617e85809726c686598ab03cfc1c79f43b56  ./ytt-linux-amd64
71b5ea38bfc7a9748c35ce0735fd6f806dce46bd5c9039d527050c7682e62a70  ./ytt-darwin-amd64
75db553804956df279d0121067f4b052c539b2fafb4d5beff11ddb6792f30775  ./ytt-windows-arm64.exe
a0e8140e1924db591994a7063dc2ea38256ee0aabda650820dd69fac8d20c077  ./ytt-windows-amd64.exe
a2d195b058884c0e36a918936076965b8efb426f7e00f6b7d7b99b82737c7299  ./ytt-linux-arm64
```

0.49.1
```
10bb753984bed1f351fb767810fdccb5def531ad77b27093f71698a44ab45965 ./ytt-darwin-amd64
20a2f7466157a9c6189e885d0027e17c48776e65627f30fe04bffeef1d6f6166 ./ytt-linux-amd64
220408ce0604309f0704bd102f216f807db56b91f37af3317beacd7621f99a16 ./ytt-windows-arm64.exe
7a8d04ac91578239d32683eea7c5bb045e6e3f0df6a8c3bb42927a161b7da4db ./ytt-linux-arm64
ac75de5a71ebd165f2b6be338a16020055d298ccb31a7dbade887d11912b8fed ./ytt-windows-amd64.exe
cba34f36d2b34108cc616a9455e8970ff10937470555af2dd09720ead9b29f64 ./ytt-darwin-arm64
```

**Comment by joaopapereira** [comment] 2024-06-12 19:37
Can you try it now?

**Comment by omarkalloush** [comment] 2024-06-12 20:02
It's working now for me 👍🏻

**Comment by joaopapereira** [comment] 2024-06-12 20:11
Cool. I updated the release with the missing spaces, and it is working now. I also checked that the GitHub action https://github.com/carvel-dev/ytt/actions/runs/9487364424/job/26149360186 is now green.
Closing the issue as it looks like it is solved, feel free to reopen if the problem is not solved for you.

**Closed as completed by joaopapereira** 2024-06-12 20:11 UTC
Labels: bug
