### ISSUE TITLE
[lang] anchors are not supported

### ISSUE THREAD

**Issue by jorgemoralespou** [k14s/ytt#186] opened 2020-08-13 13:13 UTC
I've seen #172 and the [limitations](https://github.com/k14s/ytt/blob/develop/docs/known-limitations.md) and this prevents processing/installing knative resources with ytt.

https://github.com/knative/serving/blob/6c3eb0433d235d5ba9768ada4e7be90ddeb74458/config/core/resources/configuration.yaml#L26-L55

**Comment by cppforlife** [comment] 2020-08-18 17:29
we do want them to work since they may be used within third party configuration.

**Comment by cppforlife** [comment] 2020-08-28 14:33
minimal reproduction: https://get-ytt.io/#gist:https://gist.github.com/cppforlife/f03ac62b09da71bd8549e372fb921bd6

**Comment by cppforlife** [comment] 2020-08-28 15:48
this open PR to go-yaml fixes issue: https://github.com/go-yaml/yaml/pull/364; however, after the fix cases like knative config:

```
  - << : *version
    name: v1beta1
```

present a challenge since they introduce duplicate keys.

**Comment by dprotaso** [comment] 2021-06-23 13:52
> this open PR to go-yaml fixes issue: [go-yaml/yaml#364](https://github.com/go-yaml/yaml/pull/364); however, after the fix cases like knative config:
> 
> ```
>   - << : *version
>     name: v1beta1
> ```
> 
> present a challenge since they introduce duplicate keys.

but the last key listed should just override no? I'm guessing there's something in the spec regarding the behaviour

**Comment by aaronshurley** [comment] 2021-06-23 15:56
Some additional conversation/context [in slack](https://kubernetes.slack.com/archives/CH8KCCKA5/p1624457827080600).

**Comment by pivotaljohn** [comment] 2021-06-23 16:10
Adding to list of issues to review during pre-IPM ==> recommended

**Comment by groundnuty** [comment] 2021-09-11 11:02
any progress on that? I'm attempting to port anchor heavy configurations to ytt and lack support for anchors is making it increasingly complicated

**Comment by pivotaljohn** [comment] 2021-09-20 02:47
@groundnuty asked
> any progress on that? I'm attempting to port anchor heavy configurations to ytt and lack support for anchors is making it increasingly complicated

Unfortunately not, so far.

We've been in a "wait and hope for upstream fix" for some time now. So, while technically "in progress" is correct, we're really blocked on this upstream fix... (or we decide to find a way to land it in our [own fork](https://github.com/k14s/yaml)).

It be clear, it's in the Carvel maintainer's backlog 👍🏻 , but it's currently sitting below the OpenAPI Schema export feature 🤷🏻 .

**Comment by groundnuty** [comment] 2021-09-20 08:13
@pivotaljohn maybe it's somehow connected with the memorable moment, that go-yaml stopped supporting flexible/forward anchors? It broke a lot of anchoring features... here is the discussion, where you can find a commit that broke that: https://github.com/go-yaml/yaml/issues/558 if that's the case you can just try to build with older version of go-yaml and see if it works, and if it does remove the anchor-breaking changes form your fork.

Just guessing here/trying to helpful :-)

**Comment by pivotaljohn** [comment] 2021-09-20 13:11
Appreciate that, @groundnuty. I'm looking into this.

I'll update this comment with my "research", as I go.

Facts:
- go-yaml/yaml#515 was introduced in v2.2.4 of go-yaml/yaml; `ytt` forked at v2.2.2
- fix for merge @cppforlife mentioned above was translated in 237b7e2 from go-yaml/yaml#364 (~Aug 2020)
- also noted by @cppforlife, merged result includes duplicate keys. When the file contains templating and `--implicit-map-key-overrides` is provided, the merge works as desired.
- along the way to intending to improve how plain YAML is processed by `ytt` (i.e. YAML files that do _not_ contain any templating), we short-circuit the handling of `--implicit-map-key-overrides`
  - introduced with #232 
  - defect reported in #310 (among others)
- a workaround could be to prefix any plain YAML with some inert templating (e.g. `#@ True` would do it).
- a fix is to ensure that `--implicit-map-key-overrides` applies to plain YAML as well (not just templates).

**Comment by hasufell** [comment] 2021-11-20 19:31
This also stops me from migrating [my yamls](https://github.com/haskell/ghcup-metadata) to ytt.

**Comment by pivotaljohn** [comment] 2022-01-10 19:49
FWIW, this issue was addressed on the main branch: #550 and will be included in the next release (coming soon).

**Closed as completed** 2022-05-17 19:33 UTC
Labels: enhancement, carvel triage

**Comment by pivotaljohn** [comment] 2022-05-17 19:34
Released in [v0.39.0](https://github.com/vmware-tanzu/carvel-ytt/releases/tag/v0.39.0).

**Comment by dprotaso** [comment] 2022-05-17 19:51
woot! thanks!
