### ISSUE TITLE
Annotating a schema node with a null value as "nullable" causes panic (and mayhem)

### ISSUE THREAD

**Issue by cari-lynn** [k14s/ytt#405] opened 2021-05-28 18:06 UTC
## Acceptance Criteria:
Error when assigning values to null in schema, unless annotated as `@schema/type any=True`.

### Scenario 1 (currently working on develop)

**Given** 
`config.yml`:
```
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```
`schema.yml`:
```
#@schema/match data_values=True
---
foo:
```
when executing `ytt -f . --enable-experiment-schema`
**Desired/Current Result:**
```
ytt: Error:
Invalid schema - null value not allowed here
============================================

schema.yml:
    |
  3 | foo:
    |

    = found: null value
    = expected: non-null value
    = hint: in YAML, omitting a value implies null.
    = hint: to set the default value to null, annotate with @schema/nullable.
    = hint: to allow any value, annotate with @schema/type any=True.
```

### Scenario 2

**Given** 
`config.yml`:
```
#@ load("@ytt:data", "data")
---
foo: #@ data.values.foo
```
`schema.yml`:
```
#@schema/match data_values=True
---
#@schema/nullable
foo: 
```
when executing `ytt -f . --enable-experiment-schema -v=foo=hello `
**Undesired/Current Result:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x144cd82]

goroutine 1 [running]:
github.com/k14s/ytt/pkg/schema.NullType.CheckType(0x0, 0x0, 0xc0001cd680, 
0x16d2490, 0xc000130be8, 0x152a4a0, 0xc00013f801, 0xc000130be8)
	github.com/k14s/ytt/pkg/schema/type.go:71 +0x42
    [...]
```
**Desired Result:**
```
ytt: Error:
Invalid schema - null value not allowed here
============================================

schema.yml:
    |
  3 | foo:
    |

    = found: null value
    = expected: non-null value
    = hint: in YAML, omitting a value implies null.
    = hint: to set the default value to null, annotate with @schema/nullable.
    = hint: to allow any value, annotate with @schema/type any=True.
```

---
**What steps did you take:**
Reproduction steps:
config.yml
```yaml
#@ load("@ytt:data", "data")
---
nothing: #@ data.values.nothing
```
schema.yml
```yaml
#@schema/match data_values=True
---
#@schema/nullable
nothing:
```

```bash
export STR_VAL_nothing=null
./ytt -f examples/schema/config.yml -f examples/schema/schema.yml  --data-values-env STR_VAL --enable-experiment-schema
```
**What happened:**
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x147fa22]

goroutine 1 [running]:
github.com/k14s/ytt/pkg/schema.NullType.CheckType(0x0, 0x0, 0xc00017a000, 0x1712840, 0xc00017fb40, 0x1564a80, 0xc0000dd401, 0xc00017fb40)
	github.com/k14s/ytt/pkg/schema/type.go:71 +0x42
github.com/k14s/ytt/pkg/yamlmeta.checkCollectionItem(0x151ab80, 0xc00008f820, 0x1716940, 0xc00017ef00, 0xc000140f30, 0x0, 0xc0001b4b40, 0x0)
	github.com/k14s/ytt/pkg/yamlmeta/node.go:318 +0x182
github.com/k14s/ytt/pkg/yamlmeta.(*MapItem).Check(0xc0001b5740, 0x17127c0, 0xc0001b4ba0, 0x0)
	github.com/k14s/ytt/pkg/yamlmeta/node.go:271 +0xb7
github.com/k14s/ytt/pkg/yamlmeta.(*Map).Check(0xc0001b4ba0, 0x15ac7c0, 0xc0001b4ba0, 0x171ad20)
	github.com/k14s/ytt/pkg/yamlmeta/node.go:257 +0xea
github.com/k14s/ytt/pkg/yamlmeta.(*Document).Check(0xc0001b4c00, 0x1715640, 0xc0001b4c00, 0x0)
	github.com/k14s/ytt/pkg/yamlmeta/node.go:241 +0x8f
github.com/k14s/ytt/pkg/workspace.DataValuesPreProcessing.typeAndCheck(0x0, 0x0, 0x0, 0xc0000ae100, 0x1, 0x1, 0x1712700, 0xc00017f000, 0xc0001b4cc0, 0x0, ...)
	github.com/k14s/ytt/pkg/workspace/data_values_pre_processing.go:119 +0x85
github.com/k14s/ytt/pkg/workspace.DataValuesPreProcessing.apply(0x0, 0x0, 0x0, 0xc0000ae100, 0x1, 0x1, 0x1712700, 0xc00017f000, 0xc0001b4cc0, 0x0, ...)
	github.com/k14s/ytt/pkg/workspace/data_values_pre_processing.go:68 +0x23d
github.com/k14s/ytt/pkg/workspace.DataValuesPreProcessing.Apply(0x0, 0x0, 0x0, 0xc0000ae100, 0x1, 0x1, 0x1712700, 0xc00017f000, 0xc0001b4cc0, 0x0, ...)
...
```

**What did you expect:**
Based on the [docs](https://carvel.dev/ytt/docs/latest/ytt-data-values/#overriding-data-values-via-command-line-flags) expected the result to be; `nothing: null`

**Anything else you would like to add:**
This happens because `n.GetValueType()` returns `nil`, then we try to call `CheckType()` on it.

**Environment:**

- ytt version (use `ytt --version`): ytt version 0.33.0 (built from develop (5/28/21)
- OS (e.g. from `/etc/os-release`): mac

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by pivotaljohn** [comment] 2021-05-28 22:25
I was able to reproduce.

In fact, with that schema and _any_ attempt to set the value to anything but `null` yields this panic.

Note: using a `--data-values...` without the `-yaml` suffix means that the input will be interpreted as a string. So, in the reporting example, nothing gets set to `"null"`.

So:

```console
$ ytt -f config.yml -f schema.yml --data-value-yaml nothing=null --enable-experiment-schema
$ VAL_nothing=null ytt -f config.yml -f schema.yml --data-value-env-yaml VAL --enable-experiment-schema
$ ytt -f config.yml -f schema.yml -f values.yml=<(echo -e "#@data/values\n---\nnothing: null") --enable-experiment-schema
```
All result in:
```yaml
nothing: null
```

But:

```console
$ ytt -f config.yml -f schema.yml --data-value nothing=null --enable-experiment-schema
$ ytt -f config.yml -f schema.yml --data-value-yaml nothing=string --enable-experiment-schema
$ ytt -f config.yml -f schema.yml --data-value-yaml nothing=13 --enable-experiment-schema
$ ytt -f config.yml -f schema.yml -f values.yml=<(echo -e "#@data/values\n---\nnothing: 'null'") --enable-experiment-schema
```

All panic in the way the bug report describes.

**Comment by pivotaljohn** [comment] 2021-05-28 22:48
For prioritization:
- to get here, the author needs to provide both `null` as the value _and_ annotate the node as `@schema/nullable`. I suspect this situation will be very rare.
- the workaround is cheap: the author simply provide a non-null value in the schema.

For relevance:
- regardless of how we ultimately solve this, we don't want a panic ==> carvel accepted.

**Comment by pivotaljohn** [comment] 2021-05-29 00:03
In terms of consistency within the type system:
- I can't see any practical uses for a variable that is a constant that can only be the value `null`.
- we've already indicated that `null` is not allowed as a value in schema because no type information can be inferred from it.
- the only case when `null` as a value seems to make sense to me is when that same node is `@schema/type any=True`.

My recommendation is that we solve this by making `null` an invalid value in schema for everything except `@schema/type any=True`.

Thoughts?

**Comment by pivotaljohn** [comment] 2021-06-14 16:28
It's worth taking a run at this if it's not too much of a change. ==> "Prioritized Backlog"

We've achieved rough consensus on an approach (see last comment).

**Comment by pivotaljohn** [comment] 2021-06-14 22:56
**Note:** at this time, we are aiming for GA. The probability or impact of this bug is such that we _could_ accept it as a known issue. We'd (obviously) rather fix it.

If this defect can be addressed in a day or less, let's do it. Otherwise, let's chat about what to do as a team.

**Closed as completed** 2021-07-08 23:17 UTC
Labels: bug, carvel accepted, can be replicated
